# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "05svvj0irzkcvnjfr4x529rclspc9jwx8360c0i3a8fhg3qy0888";
    x86_64-linux = "0hc5cipxmnlzni70shmkf1l8fgmbinc8zhmnzfk5mbkw8jfzqcpb";
    armv6l-linux = "0i8ws5wniz8161n2f47f2yjpb7vxxibd6cs5jb7hi747mzx2jlrp";
    armv7l-linux = "07md5rfv4dpgzjnsgnd7rah8pkhwqisifk546z5pbgdnn5iwz3a8";
    aarch64-linux = "0l7fdn3c86ab0bq6pn3v7l6ijk0kp5hzwwrvdj1al6pqg7sjz8ml";
    x86_64-darwin = "1krh92h15dkifysjczqhjk7m1p78fhf6bd85ckllyk8d3vpsw5b6";
    aarch64-darwin = "1cq211jryamqvgphw5717yizw97hqh0z6zfrvqy3qvjmf7wicz3q";
  };

  urlMap = {
    i686-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/ZenTenApp/seedify/releases/download/v1.23.0/seedify_1.23.0_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "seedify_1.23.0_Linux_i386";
    x86_64-linux = "seedify_1.23.0_Linux_x86_64";
    armv6l-linux = "seedify_1.23.0_Linux_armv6";
    armv7l-linux = "seedify_1.23.0_Linux_armv7";
    aarch64-linux = "seedify_1.23.0_Linux_arm64";
    x86_64-darwin = "seedify_1.23.0_Darwin_x86_64";
    aarch64-darwin = "seedify_1.23.0_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "seedify";
  version = "1.23.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./seedify $out/bin/seedify
    installManPage ./manpages/seedify.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
