# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0pv28f1gimr4ck1l2i61zh8gvfn6gm6w94xfh4zvxqq2imi8mpcc";
    x86_64-linux = "1zl6wqc1d9mmbqicqy9nj4qp8pbxh8h86dxph6hr2q7wadb37yyg";
    armv6l-linux = "164c4vc6xl96ddavc01gd9kwgsasf17jclz5dgzzlpskima3dzbf";
    armv7l-linux = "0j2l3yggwy48r3pq63byp5rhm4f3vfc0a5417fn8xb4w6lc3wckc";
    aarch64-linux = "1sw26nw9b9aybdp3n5pp8j52ba2q3nh41msnxwylxx15ncf28p7i";
    x86_64-darwin = "1s88lmhq8snc2cvqpfymc760ann34mgrqq75zwx7b8m2hkmg3crq";
    aarch64-darwin = "12d97r90ikap8swbb51shh76ib8idwwplbmfmxz5ahbf1hb5p6wx";
  };

  urlMap = {
    i686-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/ZenTenApp/seedify/releases/download/v1.27.0/seedify_1.27.0_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "seedify_1.27.0_Linux_i386";
    x86_64-linux = "seedify_1.27.0_Linux_x86_64";
    armv6l-linux = "seedify_1.27.0_Linux_armv6";
    armv7l-linux = "seedify_1.27.0_Linux_armv7";
    aarch64-linux = "seedify_1.27.0_Linux_arm64";
    x86_64-darwin = "seedify_1.27.0_Darwin_x86_64";
    aarch64-darwin = "seedify_1.27.0_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "seedify";
  version = "1.27.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./seedify $out/bin/seedify
    installManPage ./manpages/seedify.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
