# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "198xdwr0vnbnkylnzwc5225wqbyl3j8hcglxxvh8a5f5mshgq5rr";
    x86_64-linux = "0by9q9f0fqvg99ssq0jfipifidv37f8ayhchs5icakhidjm6awnc";
    armv6l-linux = "0yx4mizmdn8qmjrx44p323cxfj1ws8z0wbpfy8wd3k0syqj1g8rg";
    armv7l-linux = "0jw59rk370d6xdy3771xv5llgf0lw34jcm01kvn96wlp14p5jsia";
    aarch64-linux = "1hvf7dsmwrcaq9z8vxdrmhmcaps12993fl2ad05m33572yg0dykl";
    x86_64-darwin = "1zk6dbcfrykcc6cqc2q3xh79w0vvzibx9pl9k73j4fi8jf93hgkm";
    aarch64-darwin = "1c969dwyzi398lknkih1vvmh51hy42vx11fyvcqm6868ly6jszp9";
  };

  urlMap = {
    i686-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.9/meltify_0.1.9_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "meltify_0.1.9_Linux_i386";
    x86_64-linux = "meltify_0.1.9_Linux_x86_64";
    armv6l-linux = "meltify_0.1.9_Linux_armv6";
    armv7l-linux = "meltify_0.1.9_Linux_armv7";
    aarch64-linux = "meltify_0.1.9_Linux_arm64";
    x86_64-darwin = "meltify_0.1.9_Darwin_x86_64";
    aarch64-darwin = "meltify_0.1.9_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "meltify";
  version = "0.1.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./meltify $out/bin/meltify
    cp -vr ./meltify-brave $out/bin/meltify-brave
    cp -vr ./meltify-beldex $out/bin/meltify-beldex
    cp -vr ./meltify-monero $out/bin/meltify-monero
    cp -vr ./meltify-polyseed $out/bin/meltify-polyseed
    cp -vr ./meltify-info $out/bin/meltify-info
    installManPage ./manpages/meltify.1.gz
    installManPage ./manpages/meltify-brave.1.gz
    installManPage ./manpages/meltify-beldex.1.gz
    installManPage ./manpages/meltify-monero.1.gz
    installManPage ./manpages/meltify-polyseed.1.gz
    installManPage ./manpages/meltify-info.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
