# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1wrb595lh674cypnv1q2dxg6xwy1m27h7bjgh4hkbmd0vwvd235l";
    x86_64-linux = "1kvnkgjbksxwk0basw429k1gs1z4q8q3p5rfa54b6p03pxx1h7vm";
    armv6l-linux = "1r77glld7r22snbr6gln9hiclw3m40rpp8cfhpskfvdmqcr3rj2p";
    armv7l-linux = "1rnxzwynnjmj3d86wki07cp4c03sns8iznbzgvngj6bdwpli2m0y";
    aarch64-linux = "1d378c7sqg5zvh46kgnamdzv0d6p6gqgz3gb33pjiyfw21fwzpbd";
    x86_64-darwin = "0v1fhnw51abl023jqxar5mnhrmy63vmzjipvp6yyyjvfslq9m7wz";
    aarch64-darwin = "1msayp0ixcvn3v2y8fvv9i7jian0rkyfbb4gqmz0931rv1fficz2";
  };

  urlMap = {
    i686-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.14/meltify_0.1.14_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "meltify_0.1.14_Linux_i386";
    x86_64-linux = "meltify_0.1.14_Linux_x86_64";
    armv6l-linux = "meltify_0.1.14_Linux_armv6";
    armv7l-linux = "meltify_0.1.14_Linux_armv7";
    aarch64-linux = "meltify_0.1.14_Linux_arm64";
    x86_64-darwin = "meltify_0.1.14_Darwin_x86_64";
    aarch64-darwin = "meltify_0.1.14_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "meltify";
  version = "0.1.14";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./meltify $out/bin/meltify
    cp -vr ./meltify-brave $out/bin/meltify-brave
    cp -vr ./meltify-beldex $out/bin/meltify-beldex
    cp -vr ./meltify-monero $out/bin/meltify-monero
    cp -vr ./meltify-polyseed $out/bin/meltify-polyseed
    cp -vr ./meltify-info $out/bin/meltify-info
    installManPage ./manpages/meltify.1.gz
    installManPage ./manpages/meltify-brave.1.gz
    installManPage ./manpages/meltify-beldex.1.gz
    installManPage ./manpages/meltify-monero.1.gz
    installManPage ./manpages/meltify-polyseed.1.gz
    installManPage ./manpages/meltify-info.1.gz
    installShellCompletion ./completions/*
    runHook postInstall
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
