# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1wsqchyygjbwqxj5wh3kl46nsjgc8sv0xy4c5qwxw8jxjcracm1s";
    x86_64-linux = "1n30fn17s7d6wfa980gh5sbryfk3h84sj4wm0jgf9jks3lqsnkm5";
    armv6l-linux = "1hjpp7xd2z8w0cp9fj21ngry96630093ss65wp0b0bmy83k1ysf1";
    armv7l-linux = "0xgz198ndmsicsciqk9lv0b06lrhndwp765i7mi85kvp08fqx5i4";
    aarch64-linux = "12vz83ylldc9krcan652znpkkdm2npph1lzcvpyx9n4kkfrgy0w4";
    x86_64-darwin = "1p1qhlwvnlaal3ji4ivwy4zs8gdq485x1bhr8g6z9kgplipc7ikp";
    aarch64-darwin = "10az3x3nxp907y6wp4nvp06rvxqq67kwm5bs5ymb7813dajh8f5f";
  };

  urlMap = {
    i686-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/ZenTenApp/meltify/releases/download/v0.1.7/meltify_0.1.7_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "meltify_0.1.7_Linux_i386";
    x86_64-linux = "meltify_0.1.7_Linux_x86_64";
    armv6l-linux = "meltify_0.1.7_Linux_armv6";
    armv7l-linux = "meltify_0.1.7_Linux_armv7";
    aarch64-linux = "meltify_0.1.7_Linux_arm64";
    x86_64-darwin = "meltify_0.1.7_Darwin_x86_64";
    aarch64-darwin = "meltify_0.1.7_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "meltify";
  version = "0.1.7";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./meltify $out/bin/meltify
    cp -vr ./meltify-brave $out/bin/meltify-brave
    cp -vr ./meltify-beldex $out/bin/meltify-beldex
    cp -vr ./meltify-monero $out/bin/meltify-monero
    cp -vr ./meltify-polyseed $out/bin/meltify-polyseed
    cp -vr ./meltify-info $out/bin/meltify-info
    installManPage ./manpages/meltify.1.gz
    installManPage ./manpages/meltify-brave.1.gz
    installManPage ./manpages/meltify-beldex.1.gz
    installManPage ./manpages/meltify-monero.1.gz
    installManPage ./manpages/meltify-polyseed.1.gz
    installManPage ./manpages/meltify-info.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
